// Code generated by scaffold. DO NOT EDIT.
package delivery

import (
	"event_sourcing_bank_system_gateway/application/routing/delivery/handler"
	"event_sourcing_bank_system_gateway/application/routing/delivery/handler/payment"
	"event_sourcing_bank_system_gateway/package/settings"
)

type routingConfig struct {
	handler                 handler.RequestHandler
	remoteServiceName       string
	remoteServiceMethod     string
	remoteServicePermission string
}

func buildRegistry(cfg *settings.Config) map[string]routingConfig {
	return map[string]routingConfig{
		"POST:/api/v1/payment-service/payment": {
			payment.NewCreateTransactionHandler(cfg),
			"PaymentService",
			"CreateTransaction",
			"",
		},
	}
}
