// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/payment-service/transaction": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PaymentService"
                ],
                "summary": "permission:",
                "parameters": [
                    {
                        "description": "\u003cparam_description\u003e",
                        "name": "source_account_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "\u003cparam_description\u003e",
                        "name": "target_account_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "\u003cparam_description\u003e",
                        "name": "description",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "\u003cparam_description\u003e",
                        "name": "send_amount",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/event_sourcing_bank_system_gateway_proto_payment.Money"
                        }
                    },
                    {
                        "description": "\u003cparam_description\u003e",
                        "name": "idempotency_key",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Body example",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/event_sourcing_bank_system_gateway_proto_payment.CreateTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/event_sourcing_bank_system_gateway_proto_payment.CreateTransactionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "event_sourcing_bank_system_gateway_proto_payment.CreateTransactionRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "send_amount": {
                    "$ref": "#/definitions/event_sourcing_bank_system_gateway_proto_payment.Money"
                },
                "source_account_id": {
                    "type": "string"
                },
                "target_account_id": {
                    "type": "string"
                }
            }
        },
        "event_sourcing_bank_system_gateway_proto_payment.CreateTransactionResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "Deprecated: Do not use.",
                    "type": "string"
                }
            }
        },
        "event_sourcing_bank_system_gateway_proto_payment.Money": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Gateway",
	Description:      "REST -> GRPC API Gateway",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
