basePath: /
definitions:
  event_sourcing_bank_system_gateway_proto_payment.CreateTransactionRequest:
    properties:
      description:
        type: string
      idempotency_key:
        type: string
      send_amount:
        $ref: '#/definitions/event_sourcing_bank_system_gateway_proto_payment.Money'
      source_account_id:
        type: string
      target_account_id:
        type: string
    type: object
  event_sourcing_bank_system_gateway_proto_payment.CreateTransactionResponse:
    properties:
      id:
        description: 'Deprecated: Do not use.'
        type: string
    type: object
  event_sourcing_bank_system_gateway_proto_payment.Money:
    properties:
      amount:
        type: string
      currency:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST -> GRPC API Gateway
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API Gateway
  version: "1.0"
paths:
  /api/v1/payment-service/transaction:
    post:
      consumes:
      - application/json
      parameters:
      - description: <param_description>
        in: body
        name: source_account_id
        schema:
          type: string
      - description: <param_description>
        in: body
        name: target_account_id
        schema:
          type: string
      - description: <param_description>
        in: body
        name: description
        schema:
          type: string
      - description: <param_description>
        in: body
        name: send_amount
        schema:
          $ref: '#/definitions/event_sourcing_bank_system_gateway_proto_payment.Money'
      - description: <param_description>
        in: body
        name: idempotency_key
        schema:
          type: string
      - description: Body example
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/event_sourcing_bank_system_gateway_proto_payment.CreateTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/event_sourcing_bank_system_gateway_proto_payment.CreateTransactionResponse'
      summary: 'permission:'
      tags:
      - PaymentService
swagger: "2.0"
