// Code generated by scaffold. DO NOT EDIT.
package grpc

import (
	"fmt"

	"google.golang.org/grpc/metadata"

	"event_sourcing_bank_system_gateway/package/settings"
	"event_sourcing_bank_system_gateway/proto/payment"

	"event_sourcing_bank_system_gateway/package/grpc"
	"event_sourcing_bank_system_gateway/package/monitor"
	//"context"
)

func (client *paymentServiceClient) initMethodRegistry() {
	client.methodRegistry = map[string]func(interface{}, map[string]string) (interface{}, error){
		"CreateTransaction": client.createTransaction,
	}
}

type paymentServiceClient struct {
	grpcClient     payment.PaymentServiceClient
	methodRegistry map[string]func(interface{}, map[string]string) (interface{}, error)
}

func NewPaymentServiceClient(config *settings.Config) *paymentServiceClient {
	// using WithInsecure() because no SSL running
	cc, err := grpc.CreateGRPCClientConn(config.Service.PaymentServiceUrl, false)
	if err != nil {
		fmt.Println("Could not connect:", err)
	}

	client := paymentServiceClient{
		grpcClient: payment.NewPaymentServiceClient(cc),
	}
	client.initMethodRegistry()

	return &client
}

func (client *paymentServiceClient) GetMethodRegistry() map[string]func(interface{}, map[string]string) (interface{}, error) {
	return client.methodRegistry
}

func (client *paymentServiceClient) createTransaction(data interface{}, md map[string]string) (interface{}, error) {
	ctx := monitor.GetApmContext()
	//ctx := context.Background()
	for k, v := range md {
		ctx = metadata.AppendToOutgoingContext(ctx, k, v)
	}
	return client.grpcClient.CreateTransaction(ctx, data.(*payment.CreateTransactionRequest))
}
