// Code generated by scaffold. DO NOT EDIT.
package application

func (s *Server) initPublicRouting() {
	h := s.handler
	router := s.router.Group("")

	pR := router.Group("/api/v1/oms/")
	h.RegisterPublicAPI(pR)
}

func (s *Server) initPrivateRouting() {
	h := s.handler
	router := s.router.Group("")

	pR := router.Group("/api/v1/oms/")
	pR.Use(h.Authorization())
	h.RegisterPrivateAPI(pR)
}

func (s *Server) initPaymentRouting() {
	h := s.handler
	router := s.router.Group("")

	rPaymentPayment := router.Group("/api/v1/payment-service")
	rPaymentPayment.Use(h.Authorization())
	h.RegisterAPI(rPaymentPayment)
}
