// Code generated by scaffold. DO NOT EDIT.
package service

import (
	"event_sourcing_bank_system_gateway/application/routing/delivery/remote"
	"event_sourcing_bank_system_gateway/application/routing/delivery/remote/grpc"
	"event_sourcing_bank_system_gateway/package/settings"
)

func initRemoteServiceClientRegistry(config *settings.Config) map[string]RemoteServiceClient {
	return map[string]RemoteServiceClient{
		"PaymentService": remote.NewGrpcServiceClient(grpc.NewPaymentServiceClient(config)),
	}
}
