dev:
	java -cp target/distributed_system-1.0-SNAPSHOT.jar distributed_system.Main

run:
	java -cp target/distributed_system-1.0-SNAPSHOT.jar distributed_system.Main

clean:
	rm -rf target
	rm -rf log

build:
	mvn clean package

.PHONY: run clean build