version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  leader_election:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - zookeeper
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
    deploy:
      replicas: 3
volumes:
  zookeeper_data:
  redis_data:
